apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bakson_app
  namespace: argocd
spec:
  project: bakson_project
  source:
    repoURL: git@github.com:BogdanBozic/bakson_infra.git
    targetRevision: HEAD
    path: argocd/bakson_app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespaces: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true